// ═════════════════════════════════════════════════════════════════════════════════
// DESIGN TOKENS & THEME
// ═════════════════════════════════════════════════════════════════════════════════

export const COLORS = {
  blue: "#2E5BBA",
  blueDark: "#1A3A8A",
  blueLight: "#EEF3FF",
  orange: "#F47A20",
  orangeLight: "#FFF3E8",
  white: "#FFFFFF",
  gray50: "#F8F9FA",
  gray100: "#F0F2F5",
  gray200: "#E0E4EA",
  gray400: "#9BA3B0",
  gray600: "#5A6472",
  gray900: "#1A1D23",
  green: "#22C55E",
  greenLight: "#DCFCE7",
  red: "#EF4444",
  redLight: "#FEE2E2",
};

// ─── Style Helper Object ───────────────────────────────────────────────────────
export const createStyles = () => ({
  // Layout
  app: {
    fontFamily: "'Nunito', 'Segoe UI', sans-serif",
    background: COLORS.gray50,
    minHeight: "100vh",
    maxWidth: 430,
    margin: "0 auto",
    position: "relative",
    boxShadow: "0 0 40px rgba(0,0,0,0.12)",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    background: COLORS.blue,
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  logoText: {
    fontSize: 22,
    fontWeight: 800,
    color: COLORS.white,
    letterSpacing: "-0.5px",
  },
  logoUp: { color: COLORS.orange },
  content: { flex: 1, overflowY: "auto", paddingBottom: 80 },
  navBar: {
    position: "fixed",
    bottom: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "100%",
    maxWidth: 430,
    background: COLORS.white,
    borderTop: `1px solid ${COLORS.gray200}`,
    display: "flex",
    zIndex: 100,
  },
  navItem: (active) => ({
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "10px 4px 8px",
    cursor: "pointer",
    color: active ? COLORS.blue : COLORS.gray400,
    fontWeight: active ? 700 : 500,
    fontSize: 11,
    gap: 3,
    transition: "color 0.15s",
    background: "none",
    border: "none",
  }),
  // Cards
  card: {
    background: COLORS.white,
    borderRadius: 16,
    padding: "16px",
    marginBottom: 12,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  pill: (color, bg) => ({
    display: "inline-block",
    background: bg,
    color: color,
    borderRadius: 20,
    padding: "3px 10px",
    fontSize: 12,
    fontWeight: 700,
  }),
  btn: (primary = true, small = false) => ({
    background: primary ? COLORS.blue : COLORS.white,
    color: primary ? COLORS.white : COLORS.blue,
    border: primary ? "none" : `2px solid ${COLORS.blue}`,
    borderRadius: 12,
    padding: small ? "8px 16px" : "13px 20px",
    fontWeight: 700,
    fontSize: small ? 13 : 15,
    cursor: "pointer",
    width: primary && !small ? "100%" : "auto",
    fontFamily: "inherit",
    transition: "opacity 0.15s, transform 0.1s",
  }),
  btnOrange: (small = false) => ({
    background: COLORS.orange,
    color: COLORS.white,
    border: "none",
    borderRadius: 12,
    padding: small ? "8px 16px" : "13px 20px",
    fontWeight: 700,
    fontSize: small ? 13 : 15,
    cursor: "pointer",
    width: small ? "auto" : "100%",
    fontFamily: "inherit",
  }),
  btnDanger: {
    background: COLORS.redLight,
    color: COLORS.red,
    border: "none",
    borderRadius: 12,
    padding: "8px 16px",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 12,
    border: `2px solid ${COLORS.gray200}`,
    fontSize: 15,
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box",
    color: COLORS.gray900,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 800,
    color: COLORS.gray900,
    marginBottom: 12,
  },
  toast: (show) => ({
    position: "fixed",
    bottom: 90,
    left: "50%",
    transform: `translateX(-50%) translateY(${show ? 0 : 20}px)`,
    opacity: show ? 1 : 0,
    background: COLORS.gray900,
    color: COLORS.white,
    padding: "12px 24px",
    borderRadius: 24,
    fontWeight: 700,
    fontSize: 14,
    zIndex: 999,
    transition: "all 0.3s",
    pointerEvents: "none",
    whiteSpace: "nowrap",
    maxWidth: 350,
    textAlign: "center",
  }),
});
